name: muslim_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  flutter_svg: 1.1.0
  sliding_up_panel: 2.0.0+1
  file_picker: 4.6.1
  http: 0.13.4
  web_scraper: 0.1.4
  flutter_widget_from_html_core: 0.8.5+3
  webview_flutter: 3.0.4
  audio_session: 0.1.7
  rxdart: 0.27.4
  in_date_utils: 1.0.3
  intl: 0.17.0
  just_audio: 0.9.24
  music_visualizer: 1.0.2
  draggable_fab: 0.1.4
  flutter_spinkit: 5.1.0
  arabic_numbers: 1.0.0
  table_calendar: 3.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: MeQuran
      fonts: 
        - asset: fonts/me_quran.ttf
  assets: 
    - assets/images/
    - assets/icons/
    - assets/icons/navbar/
    - assets/icons/time/
  uses-material-design: true

